
NAME		= contact
SRCSDIR		= .
OBJSDIR		= objs
INCLUDES	= Contacts.h

SRCS		= Contact.cpp Phonebook.cpp

CC			= clang++
CFLAGS		= -Wall -Wextra -Werror -std=c++98

all: $(NAME)

$(NAME): $(SRCSDIR)/$(SRCS)
	@echo "Compiled success $@"
	@$(CC) $(CFLAGS) -o $@ $^

clean:

fclean: clean
	rm -rf $(NAME)

re: fclean all

.PHONY: all clean fclean re test
